### PR TITLE
after update exif-gps also update MediaDB

### PR DESCRIPTION
**Pull request by k3b**
After using FineGeotag my geo-aware gallery app [APhotoManager](https://github.com/k3b/APhotoManager/) did not show the new geo infos because the android MediaDB did not know about the modified gps data.

I fixed this.

Note before merging:

I also increased gradle-version and android-build-tools and added a compatible travis-buildserver-file.

If you do not like to change the versions only merge the java-file

### CODE REVIEW

**Comment by M66B** [comment]
Thanks for looking into this.

However, the problem is bigger than this:
- FineGeotag assumes the NEW_PICTURE intent carries a file name to the picture, whereas it could actually be an URI to a file stored using a content provider
- Android N will stop sending the NEW_PICTURE intent altogether: https://developer.android.com/preview/features/background-optimization.html#media-broadcasts

This means that the way FineGeotag handles new pictures needs to be structurally changed. I could merge this pull request, except the travis build stuff, but it would just be a temporary solution. Given that the interest in FineGeotag is quite limited, I am not sure if I want to keep maintaining it.

**Comment by k3b** [comment]
I think that even "a temporary solution" is helpful unless android-n devices are available. 

Sorry to hear about "limited interest" in your app. :-(

For me its sourcecode was quite valuable to see how to access non-android-standard-exif attributes in ExifInterfaceEx.java

**Comment by M66B** [comment]
It won't be long until Android N is available. Like many other people I already run the Android N preview version, also to test the software I develop, like my open source [NetGuard](https://github.com/M66B/NetGuard/).

**Comment by mairsbw** [comment]
Any update on this? I just noticed this bug right now trying to make sure I have everything set up. I can help with testing if that would help.

**Comment by M66B** [comment]
FineGeoTag is not supported anymore, sorry.

**Comment by k3b** [comment]
@mairsbw you can compile https://github.com/k3b/FineGeotag that contains my fix yourselft and use that, as i have done it.

**Pull request closed without merging**
