### PR TITLE
Create strings.xml

### PR DESCRIPTION
**Pull request by an0n981**

### CODE REVIEW

**Comment by M66B** [comment]
GitHub didn't notify me of this pull request, so this is why I just saw it.

**Comment by M66B** [comment]
Maybe you want to translate BackPackTrack II too (no obligations):
https://github.com/M66B/BackPackTrackII/

**Comment by an0n981** [comment]
Of course, will do

**Comment by M66B** [comment]
Thanks!
I have just released a new version of FineGeotag in the Play store, so you will get an update in a few hours.
Do you use BackPackTrack II? Any comments?

**Comment by an0n981** [comment]
Not yet, I will during my next expedition in late July

**Comment by M66B** [comment]
Maybe it is a good idea to help me test now to make sure everything works in July. More eyes will find more bugs. And maybe I can implement suggested features as well.

**Comment by an0n981** [comment]
Touché

**Pull request merged**
