### PR TITLE
Build with circleCi

### PR DESCRIPTION
**Pull request by zoff99**
make it easier for people to fork/build/merge

https://circleci.com/gh/zoff99/FineGeotag/5#artifacts

https://circle-artifacts.com/gh/zoff99/FineGeotag/5/artifacts/0/tmp/circle-artifacts.bUTfPTg/capture002.png

### CODE REVIEW

**Comment by M66B** [comment]
Sorry, but I only support the tools I use myself and that is Android Studio.

**Comment by zoff99** [comment]
it does not hurt to put this file in?
why would you dismiss this?

**Comment by M66B** [comment]
Because somebody else can ask support about this and I cannot provide it.

**Comment by zoff99** [comment]
it's a shame that you would dismiss this so quickly.
what support are you giving?

it would be helpful for people without a build system, to build the app online for free.

capture002

**Comment by M66B** [comment]
You can always make a fork and support it yourself.

Zoff notifications@github.com schreef op 29 april 2016 14:17:00 CEST:

**Pull request closed without merging**
